### ISSUE TITLE
 Issue with the application

### ISSUE THREAD

**Issue by sghqz** [MRDEADRIM/share_mouse_sound#1]
NOT WORKING

**Comment by MRDEADRIM** [comment]
Let me know how you try to run it.

**Comment by sghqz** [comment]
the mouse part seems to be working, but the audio is not getting shared !!

**Comment by MRDEADRIM** [comment]
Is there any issue showing ??

**Comment by sghqz** [comment]
not showing any issues

**Comment by sghqz** [comment]
![image](https://github.com/MRDEADRIM/Share_Mouse_Sound/assets/91407883/850e6cd3-f3bf-4dd6-ab1e-498999e1a7e6)
few errors

**Comment by MRDEADRIM** [comment]
If ubundu "apt install alsa"

**Comment by MRDEADRIM** [comment]
Try this also apt search alsa-utils

**Comment by MRDEADRIM** [comment]
Is it fixed.

**Comment by MRDEADRIM** [comment]
this issue not related to application (above related to system issue)

**Comment by MRDEADRIM** [comment]
@sghqz Let me know if any ,other issue where found.
